name: Test
on:
  push:
  schedule:
    - cron: '10 16 * * *'

jobs:
  phpunit:
    name: PHPUnit tests on ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        php: [ '8.1', '8.2' ]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - run: composer update --no-progress
      - run: vendor/bin/phpunit